pre-release-replacements = [
    {file="CHANGELOG.md", search="## Unreleased", replace="## {{version}} - {{date}}", exactly=1},
]
post-release-replacements = [
    {file="CHANGELOG.md", search="# four-cc Change Log", replace="# four-cc Change Log\n\n## Unreleased", exactly=1},
]
